# Generated by Django 5.0 on 2024-08-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shekinah', '0002_alter_lifeperformance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeperformanceimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
    ]
