# Generated by Django 5.0 on 2024-02-11 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_alter_headerinfo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField()),
                ('images', models.FileField(upload_to='media/AudioMessages')),
                ('seriesDescription', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AudioMessages',
            },
        ),
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField()),
                ('images', models.FileField(upload_to='media/videoMessages')),
                ('seriesDescription', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name_plural': 'VideoMessages',
            },
        ),
    ]
