# Generated by Django 5.0 on 2024-03-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomessage',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'VideoMessages'},
        ),
        migrations.RemoveField(
            model_name='videomessage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='videomessage',
            name='seriesDescription',
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
