# Generated by Django 5.0 on 2024-06-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_alter_audiomessage_seriesdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomessage',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'AudioMessages'},
        ),
    ]
