# Generated by Django 4.2.7 on 2023-11-20 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("class_id", models.PositiveIntegerField()),
                ("slug", models.SlugField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.TextField(blank=True)),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("description", models.TextField()),
                ("location", models.TextField()),
                ("image", models.ImageField(upload_to="EventsImage")),
                ("register_link", models.URLField(max_length=700)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["name"],
            },
        ),
    ]
