# Generated by Django 4.2.7 on 2023-12-01 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="class_id",
        ),
    ]
