# Generated by Django 4.2.7 on 2023-12-01 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_remove_event_class_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
    ]
