# Generated by Django 4.2.7 on 2023-12-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_event_duration_remove_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
