# Generated by Django 5.0 on 2023-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='button_text',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='register_link',
            field=models.URLField(blank=True, max_length=700),
        ),
    ]
