# Generated by Django 5.1.2 on 2025-09-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
