# Generated by Django 4.2.6 on 2023-11-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Accounts'},
        ),
    ]
