# Generated by Django 5.0 on 2024-10-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_products_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
