# Generated by Django 5.0 on 2024-10-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.product')),
            ],
            options={
                'verbose_name': 'Product Dimension',
                'verbose_name_plural': 'Product Dimensions',
            },
        ),
        migrations.CreateModel(
            name='ProductDimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Product Dimension value (maximum of 255 words', max_length=255, verbose_name='value')),
                ('Dimension', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.productdimension')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Product Dimension Value',
                'verbose_name_plural': 'Product Dimension Values',
            },
        ),
    ]
