# Generated by Django 5.0 on 2024-10-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_productdimension_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
