# Generated by Django 5.1.2 on 2025-09-17 02:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="HeaderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_text", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "HeaderInfos",
            },
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("images", models.FileField(upload_to="media/leader")),
                ("position", models.TextField()),
                ("bio", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Leaders",
            },
        ),
        migrations.CreateModel(
            name="LeaderSocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socialMediaName", models.CharField(max_length=255)),
                ("link", models.URLField(max_length=500)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadersocialmedias",
                        to="core.leader",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LeaderSocialMedias",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("address", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.FileField(upload_to="Locations_thumbmail")),
                ("directions", models.URLField(blank=True)),
                ("tel", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="ServiceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=500)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_days",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ServiceDays",
            },
        ),
    ]
