# Generated by Django 4.2.7 on 2023-11-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_status_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="location_class",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
