# Generated by Django 4.2.7 on 2023-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_location_category_location_location_class"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="address",
            new_name="center",
        ),
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(default="", upload_to="Locations"),
            preserve_default=False,
        ),
    ]
