# Generated by Django 4.2.7 on 2023-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_address_location_center_location_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="center",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="category",
            name="class_id",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="class_id",
        ),
        migrations.RemoveField(
            model_name="location",
            name="class_id",
        ),
        migrations.RemoveField(
            model_name="location",
            name="location_class",
        ),
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
