# Generated by Django 4.2.7 on 2023-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_center_location_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="thumbnail",
            field=models.ImageField(default=0, upload_to="Locations_thumbmail"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(upload_to="Locations_images"),
        ),
    ]
