# Generated by Django 4.2.7 on 2023-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_location_thumbnail_alter_location_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="email",
            field=models.EmailField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="tel",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
