# Generated by Django 4.2.7 on 2023-12-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_location_email_location_tel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ServiceDays",
            },
        ),
    ]
