# Generated by Django 5.0 on 2023-12-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_serviceday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='images',
            field=models.FileField(upload_to='media/leader'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.FileField(upload_to='Locations_images'),
        ),
    ]
