# Generated by Django 5.0 on 2023-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_leader_images_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='thumbnail',
            field=models.FileField(upload_to='Locations_thumbmail'),
        ),
    ]
