# Generated by Django 5.0 on 2023-12-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_location_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceday',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_days', to='core.location'),
        ),
    ]
