# Generated by Django 5.0 on 2023-12-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_headerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialMediaName', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('Leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='core.leader')),
            ],
            options={
                'verbose_name_plural': 'LeaderSocialMedias',
            },
        ),
    ]
