# Generated by Django 5.0 on 2023-12-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_leadersocialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadersocialmedia',
            name='Leader',
        ),
        migrations.AddField(
            model_name='leadersocialmedia',
            name='leader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='leadersocialmedias', to='core.leader'),
            preserve_default=False,
        ),
    ]
