# Generated by Django 5.0 on 2023-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_leadersocialmedia_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerinfo',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
