# Generated by Django 5.0 on 2024-10-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_category_created_at_alter_leader_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
