# Generated by Django 5.1.2 on 2025-09-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_location_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadersocialmedia",
            name="link",
            field=models.URLField(max_length=500),
        ),
    ]
