# Generated by Django 5.1.2 on 2025-09-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_leadersocialmedia_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceday",
            name="time",
            field=models.CharField(max_length=500),
        ),
    ]
