# Generated by Django 4.2.6 on 2023-11-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchMessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomessage',
            options={'verbose_name_plural': 'AudioMessages'},
        ),
        migrations.AlterModelOptions(
            name='videomessage',
            options={'verbose_name_plural': 'VideoMessages'},
        ),
    ]
