# Generated by Django 4.2.7 on 2023-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churchMessages", "0002_alter_audiomessage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiomessage",
            name="file",
        ),
        migrations.AddField(
            model_name="audiomessage",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="audiomessage",
            name="year",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="videomessage",
            name="year",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="videomessage",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
