# Generated by Django 4.2.7 on 2023-11-19 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("churchMessages", "0003_remove_audiomessage_file_audiomessage_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiomessage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="videomessage",
            name="author",
        ),
    ]
