# Generated by Django 4.2.7 on 2023-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churchMessages", "0004_remove_audiomessage_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiomessage",
            name="link",
        ),
        migrations.RemoveField(
            model_name="videomessage",
            name="link",
        ),
        migrations.AddField(
            model_name="audiomessage",
            name="video_id",
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videomessage",
            name="video_id",
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
