# Generated by Django 4.2.7 on 2023-11-27 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "churchMessages",
            "0005_remove_audiomessage_link_remove_videomessage_link_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiomessage",
            old_name="video_id",
            new_name="audio_id",
        ),
    ]
