# Generated by Django 4.2.7 on 2023-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churchMessages", "0007_remove_audiomessage_class_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiomessage",
            name="year",
        ),
        migrations.RemoveField(
            model_name="videomessage",
            name="year",
        ),
        migrations.AddField(
            model_name="audiomessage",
            name="ItemNumber",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videomessage",
            name="ItemNumber",
            field=models.IntegerField(default=0),
        ),
    ]
