# Generated by Django 4.2.7 on 2023-12-05 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("churchMessages", "0009_audiomessage_seriesdescription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiomessage",
            name="Category",
        ),
        migrations.RemoveField(
            model_name="audiomessage",
            name="audio_id",
        ),
        migrations.RemoveField(
            model_name="videomessage",
            name="Category",
        ),
        migrations.RemoveField(
            model_name="videomessage",
            name="video_id",
        ),
    ]
