# Generated by Django 5.0 on 2024-03-03 08:36

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testifer_names', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=20)),
                ('Testifer_center', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Intro', models.CharField(max_length=360)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='bigTestImg')),
                ('caption', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TestimonyImages',
            },
        ),
    ]
