# Generated by Django 5.0 on 2024-11-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('ministry', models.CharField(blank=True, max_length=255)),
                ('godhouse_location', models.CharField(blank=True, max_length=50)),
                ('local_church', models.TextField(blank=True)),
                ('ministry_status', models.CharField(blank=True, max_length=50)),
                ('how_did_you_know', models.CharField(blank=True, max_length=50)),
                ('how_will_you_attend', models.CharField(blank=True, max_length=50)),
                ('need_accommodation', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wwc2024/')),
                ('fileType', models.CharField(max_length=10)),
            ],
        ),
    ]
