# Generated by Django 5.1.2 on 2025-09-17 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                ("description2", models.TextField()),
                ("slogan", models.CharField(max_length=500)),
                ("image", models.FileField(null=True, upload_to="media/Churches")),
                ("Bible_verse", models.TextField()),
                ("quote", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Churches",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                ("images", models.FileField(upload_to="media/unit")),
            ],
            options={
                "verbose_name_plural": "Units",
            },
        ),
    ]
