# Generated by Django 4.2.6 on 2023-11-14 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='media/unit')),
            ],
            options={
                'verbose_name': 'Churches',
            },
        ),
    ]
