# Generated by Django 4.2.7 on 2023-12-01 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communnity", "0003_alter_church_options_alter_unit_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="church",
            name="class_id",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="class_id",
        ),
    ]
