# Generated by Django 5.0 on 2023-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0004_remove_church_class_id_remove_unit_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='images',
            field=models.ImageField(upload_to='media/church'),
        ),
    ]
