# Generated by Django 5.0 on 2023-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0006_alter_church_images_alter_unit_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='images2',
            field=models.FileField(default='', upload_to='media/church'),
            preserve_default=False,
        ),
    ]
