# Generated by Django 5.0 on 2023-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0008_remove_church_images2_church_bible_verse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='images',
            field=models.FileField(upload_to='media/churches'),
        ),
    ]
