# Generated by Django 5.0 on 2023-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0010_remove_church_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='image',
            field=models.FileField(null=True, upload_to='media/Churches'),
        ),
    ]
