# Generated by Django 5.0 on 2024-10-07 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communnity', '0012_alter_church_created_at_alter_unit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
