# Generated by Django 4.2.7 on 2023-12-04 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_enquire_prayerre_delete_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PrayerRe",
            new_name="PrayerRequest",
        ),
        migrations.AlterModelOptions(
            name="prayerrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "PrayerRequests",
            },
        ),
    ]
