# Generated by Django 5.0 on 2024-03-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.FileField(blank=True, upload_to='testimonyImage'),
        ),
    ]
