# Generated by Django 4.2.6 on 2023-11-13 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Testifer_names', models.CharField(max_length=500)),
                ('Testifer_images', models.ImageField(upload_to='testomy')),
                ('Testifer_center', models.TextField()),
                ('testimony_content', models.TextField()),
                ('uploaded_at', models.DateField()),
            ],
            options={
                'verbose_name': 'VideoMessages',
            },
        ),
    ]
