# Generated by Django 4.2.6 on 2023-11-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': 'Testimonies'},
        ),
    ]
