# Generated by Django 4.2.7 on 2023-11-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimony", "0003_alter_testimony_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bigTestImg")),
            ],
            options={
                "verbose_name_plural": "TestimonyImages",
            },
        ),
    ]
