# Generated by Django 4.2.7 on 2023-11-28 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testimony", "0004_testimonyimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimony",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name_plural": "Testimonies",
            },
        ),
    ]
