# Generated by Django 4.2.7 on 2023-11-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimony", "0005_alter_testimony_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonyimage",
            name="class_number",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
