# Generated by Django 4.2.7 on 2023-12-01 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testimony", "0006_testimonyimage_class_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimony",
            name="class_id",
        ),
    ]
