# Generated by Django 4.2.6 on 2023-11-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Blogs'},
        ),
    ]
