# Generated by Django 4.2.6 on 2023-11-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategories',
        ),
        migrations.AlterModelOptions(
            name='blogcategories',
            options={'verbose_name': 'BlogCategory', 'verbose_name_plural': 'BlogCategories'},
        ),
    ]
