# Generated by Django 4.2.7 on 2023-11-20 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_category_blogcategories_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
