# Generated by Django 4.2.7 on 2023-12-01 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_delete_blogcategories_blog_class_id_blog_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="class_id",
        ),
    ]
