# Generated by Django 5.0 on 2024-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WholeWordConference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='how_did_you_know',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='how_will_you_attend',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='ministry_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='need_accommodation',
            field=models.CharField(max_length=3),
        ),
    ]
