# Generated by Django 5.0 on 2024-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WholeWordConference', '0002_alter_attendee_how_did_you_know_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wwc2024/')),
                ('fileType', models.CharField(max_length=10)),
            ],
        ),
    ]
