# Generated by Django 5.0 on 2024-03-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WholeWordConference', '0003_fieldmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='location',
        ),
    ]
